### ISSUE TITLE
Working ?

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/PocketHungerGames#1]
:)

**Comment by keithkfng** [comment]
Not yet, it's still in development. Would you like to help?

**Comment by Jelly9912** [comment]
Yeah, sure
Tell me what i can do

**Comment by keithkfng** [comment]
Well, we still need to finish the main class. @Legoboy0215 is working on that as well, but you can take over development if you wish. I'll just add you to the collaborators list, and you can get cracking!

**Comment by Jelly9912** [comment]
First of all I can I download the code and try to do something, then it will test .

**Comment by keithkfng** [comment]
That's alright. Go ahead.

**Comment by Jelly9912** [comment]
Can you give me main class from @Legoboy0215

**Comment by legoboy0215** [comment]
Not ready yet, obviously. I got a huge test coming soon.

**Comment by Jelly9912** [comment]
But i can add something into your code and test it :D 
now i have a lot of time and i felt a little bored so i can do something with this main class :)
